site_name: Apuntes

site_author: Eduardo Magrané
site_description: >-
  Página con apuntes de programación y linux

site_url: https://lesolivex.com/apuntes
docs_dir: docs/

theme:
  name: material
  language: es
  logo: assets/logo.png

  features:
    - navigation.top
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.indexes
    - header.autohide
    - content.code.copy
    - navigation.footer

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black

  markdown_extensions:
    - pymdownx.highlight:
      anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - admonition
    - pymdownx.details
    - pymdownx.keys

  plugins:
    - search

  copyright: lesolivex.com 2022

  extra_css:
    - extra.css
